//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _07PC_MVC.Models.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abouts
    {
        public int AboutId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Ability1 { get; set; }
        public string Ability2 { get; set; }
        public string Ability3 { get; set; }
        public Nullable<int> InsurancePolicies { get; set; }
        public Nullable<int> SkilledAgents { get; set; }
        public Nullable<int> AwardsWon { get; set; }
        public Nullable<int> TeamMembers { get; set; }
        public string ImageUrl { get; set; }
    }
}
